config/routes.rb
Rails.application.routes.draw do
  get 'statics/team'
  get 'statics/favoris'
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'home#index'

  resources :places do
    resources :pictures, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :addresses

  resources :admins, only: [:index]
  #get 'dashboard_test', to: "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  layout "application"
  before_action :authenticate_user!
  
  def team
  	
  end

  def favoris
  	@likes = Like.where(user_id: current_user.id)
    # @user_like = Like.where(user_id: current_user.id)
    # @like = []
    # @user_like.each do |likes|
    #   @like << Place.where(id: like.place_id) 
    # end
   
  end	

end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/favoris.html.erb
<section class="matches-index pt-5">
	<div class="container">

<% if @likes.empty? %>
<h2>Vous n'avez pas de favoris</h2>
<% else %>

<div class="row matches">
  <% @likes.each do |like| %>

  <div class="col-lg-4 col-md-6 matches-item">
    <div class="card text-white">
        <% if like.place.pictures.attached? %>
        <%= image_tag place.pictures.first, class:"d-block w-100 card-bg-img" %>
        <% else %>
        <%= image_tag "coffee-shop.jpg", class:"d-block w-100 card-bg-top" %>
      <% end %>
      <div class="place-infos">
        <div class="col-6 place-title">
          <h5 class="card-title"><%= link_to like.place.name, place_path(like.place) %></h5>
        </div>
        <div class="col-6 place-badges">
          <div class="d-flex justify-content-around align-items-center pb-2">
            <% if like.place.wifi %>
            <div class="icons-box">
              <div class="icon">
                <i class="fas fa-wifi"></i>
              </div>
            </div>
            <% end %>
            <% if like.place.e_outlet %>
            <div class="icons-box">
              <div class="icon">
                <i class="fas fa-plug"></i>
              </div>
            </div>
            <% end %>
          </div>
          
          <div class="d-flex justify-content-center">
            <span class="badge badge-pill badge-pill-info"><i class="fas fa-music"></i> <%= like.place.vibe %></span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

<% end %>
	</div>
</section>

app/views/statics/team.html.erb
<br><br><br>

      <div class="container team-page">
        <div class="section-header">
          <h3>Equipe</h3>
          <p>L'équipe formidable à la base de cette application merveilleuse</p>
        </div>

        <div class="row">

          <div class="col-lg-4 col-md-6 wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
            <div class="member">
	    				<%= image_tag "team/emma.png", class:"img-fluid" %>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Emma Calvet</h4>
                  <span>Chief Executive Officer</span>
                  
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
            <div class="member">
	    				<%= image_tag "team/hicham.png", class:"img-fluid" %>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Hich-hich</h4>
                  <span>Product Manager</span>
                  
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
            <div class="member">
	    				<%= image_tag "team/charles.png", class:"img-fluid" %>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Charles Dutheil</h4>
                  <span>CTO</span>
                  
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
            <div class="member">
	    				<%= image_tag "team/jimmy.png", class:"img-fluid" %>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Jimmy Charpagne</h4>
                  <span>Accountant</span>
                  
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeInUp;">
            <div class="member">
	    				<%= image_tag "team/karel.png", class:"img-fluid" %>              
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Karel Cloarec</h4>
                  <span>Accountant</span>
                  
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    
<br><br><br>