config/routes.rb
Rails.application.routes.draw do
  get 'statics/team'
  get 'statics/favoris'
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'home#index'

  resources :places do
    resources :pictures, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :addresses

  resources :admins, only: [:index]
  #get 'dashboard_test', to: "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord

	has_many_attached :pictures
  belongs_to :address

  validates :name, presence: true
	validates :description, presence: true
	validates :address_id, presence: true

  validates :vibe, inclusion: { in: %w(hip_hop classic exotique lounge electronique pop) } 

  

  
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  
  def index
    @places = Place.all
    @user_like = Like.where(user_id: current_user.id)
    @like = []
    @user_like.each do |like|
      @like << like.place_id
    end 

  end

  def new
  end

  def create
  end

  def edit
    @place = Place.find(params[:id])  
  end

  def show
    @place = Place.find(params[:id])
    @user_like = Like.where(user_id: current_user.id)
    @like = []
    @user_like.each do |like|
      @like << like.place_id
    end 
  end


  def update
    @place = Place.find(params[:id])  
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_path(@place) }
        # format.json { render :edit, status: :ok }
      else
        format.html { render :edit }
        # format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end


  def place_params
    params.require(:place).permit(:name, :description, :wifi, :vibe, :vegan, :access_handi, :price, :e_outlet, images: [])
  end


end

app/helpers/places_helper.rb
module PlacesHelper

    public

    def url_map
        url= "<iframe width=\"100%\" height=\"350\" frameborder=\"0\" style=\"border:0\"
        src=\"https://www.google.com/maps/embed/v1/place?key=#{ENV['KEY_GOOGLE_MAP']}&q=#{current_address.latitude},#{current_address.longitude}\" allowfullscreen></iframe>"
    end

    def places_match
        @all_places = Array.new
        @select_places = Array.new
        @tmp_places = Array.new 

        store_all_places(@all_places)
        @tmp_places = @all_places
        keep_wifi_places
        keep_price_places
        keep_eOutlet_places
        keep_access_handi_places
        keep_vibe_places
        keep_vegan_places
        cut_array(sort_by_distance(@tmp_places).reverse)
      end
    
      def place_closer
        sort_by_distance(@all_places)
        @all_places.last
      end
    
      def place_top_fav
        places_all = Array.new
        store_all_places(places_all)
        places_all.sort_by!{|place| place.liked_count}
        places_all.last
      end

      private

      def cut_array(array)
        if (array.length > 3)
          return array[0, 3]
        end
        return array
      end
    
      def sort_by_distance(array_of_places)
        array_of_places.sort_by!{ |place| address_of_place(place).bearing_from(address_of_user(current_user))}
      end
    
      def address_of_place(place)
        Address.find(place.address_id)
      end
    
      def address_of_user(user)
        Address.find(current_user.address_id)
      end
    
      def keep_wifi_places
        @tmp_places.each do |place|
          if ((place.wifi != current_user.wifi) && (current_user.wifi))
            if (@tmp_places.length > 3)
              delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_price_places
        @tmp_places.each do |place|
          if (place.price != current_user.price) && (!current_user.price)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_eOutlet_places
        @tmp_places.each do |place|
          if (place.e_outlet != current_user.e_outlet) && (current_user.e_outlet)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_access_handi_places
        @tmp_places.each do |place|
          if (place.access_handi != current_user.access_handi) && (current_user.access_handi)
            delete_place_from_array(place, @tmp_places)
          end
        end
        return nil
      end
    
      def keep_vibe_places
        @tmp_places.each do |place|
          if (place.vibe != current_user.vibe)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_vegan_places
        @tmp_places.each do |place|
          if (place.vegan != current_user.vegan)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def delete_place_from_array(place, array)
        index_of_place = array.index(place)
        array.slice!(index_of_place)
        return nil
      end
    
      def store_all_places(places_array)
        Place.all.each do |place|
          places_array.push(place)
        end
      end
    
     
   
    def current_place
        Place.find(params[:id])
    end
    
    def current_address
        Address.find(current_place.address_id)
    end

    
end

app/views/places/components/_comments.html.erb
<!-- COMMENTS WITH DISQUS -->
<section class="px-3">
    <div id="disqus_thread"></div>
  </section>
  <script>
  
  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
  
  var disqus_config = function () {
  this.page.url = request.original_url;  // Replace PAGE_URL with your page's canonical URL variable
  this.page.identifier = request.original_url; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  
  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://work-and-koffee.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/places/components/_header_place_show.html.erb
<section class="clearfix carousel-place-show">
	<div id="show-header">

		<div class="header-info d-flex">

			<div class="col-8 d-flex align-items-center">
				<h2><%= @place.name %></h2>
			</div>

			<div class="col-4 header-btn pr-2">

				<% if @like.include?(@place.id) %>
					<%= button_to 'Supprimer des favoris', place_like_path(@place, current_like_id), class: "btn-fav scrollto", method: :delete %>
				<% else %>
					<%= button_to "Ajouter aux favoris", place_likes_path(@place), class: "btn-fav scrollto", method: :post %>
				<% end %>
			</div>

		</div>

		<% if current_user.try(:admin?) %>
		<div class="row admin-header-btn pr-2">

				<%= link_to 'Modifier', edit_place_path(@place.id), class:"btn btn-edit scrollto"%>
				<%= form_tag url_for(action: 'destroy'), method: "delete" do%>
					<%= submit_tag "Supprimer ce lieu", class: 'btn btn-delete'%>
				<%end%>

		</div>
		<% end %>

		<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
			<% if @place.pictures.attached? %>

			<ol class="carousel-indicators">
				<% @place.pictures.each_with_index do |photo, n| %>
				<li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
				<% end %>
			</ol>

			<div class="carousel-inner">

				<div class="carousel-item active">
					<%= image_tag @place.pictures.first, alt: 'picture', class:"d-block w-100"  %>
				</div>

				<% @place.pictures.drop(1).each do |pic| %>
				<div class="carousel-item">
					<%= image_tag pic, alt: 'picture', class:"d-block w-100" %>
				</div>
				<% end %>
			</div>

			<% else %>

			<div class="carousel-inner">
				<div class="carousel-item active">
					<%= image_tag "coffee-shop.jpg", class:"d-block w-100" %>
				</div>
				<div class="carousel-item">
					<%= image_tag "grands-enfants.jpg", class:"d-block w-100" %>
				</div>
			</div>

			<% end %>

		</div>
	</div>


	</div>
</section>

app/views/places/components/_location_place.html.erb
<div class="row place-location mt-5">
  <h4>Se rendre à <%=@place.name%> :</h4>
  <div class="col-lg-12 content">
    <%= url_map.html_safe %>
  </div>

</div>

app/views/places/components/_portfolio_places.html.erb
<div class="row matches">
  <% places_match.each do |place| %>

  <div class="col-lg-4 col-md-6 matches-item">
    <div class="card text-white">
      <%= image_tag "coffee-shop.jpg", class:"d-block w-100 card-bg-img" %>
      <div class="place-infos">
        <div class="col-6 place-title">
          <h5 class="card-title"><%= link_to place.name, place_path(place.id) %></h5>
        </div>
        <div class="col-6 place-badges">
          <div class="d-flex justify-content-around align-items-center pb-2">
            <% if place.wifi %>
            <div class="icons-box">
              <div class="icon">
                <i class="fas fa-wifi"></i>
              </div>
            </div>
            <% end %>
            <% if place.e_outlet %>
            <div class="icons-box">
              <div class="icon">
                <i class="fas fa-plug"></i>
              </div>
            </div>
            <% end %>
          </div>
          <div class="place-like">
             <% if @like.include?(place.id) %>
              <div class="icons-box-like">
                <div class="icon">
                  <i class="fas fa-heart"></i>
                </div>
              </div>
              <% end %>
            </div>  
          <div class="d-flex justify-content-center">
            <span class="badge badge-pill badge-pill-info"><i class="fas fa-music"></i> <%= place.vibe %></span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/places/components/_presentation_place.html.erb
<div class="row about-container place-description mb-3">

	<div class="col-lg-7 content mb-4">
		<p> <%= @place.description %> </p>
	</div>

	<div class="col-lg-5 content mb-3">

		<div class="d-flex justify-content-around">

			<div class="icons-box">
				<% if @place.wifi %>
				<div class="icon">
					<i class="fas fa-wifi"></i>
				</div>
				<% else %>
				<div class="icon-false">
					<i class="fas fa-wifi"></i>
				</div>
				<% end %>
			</div>

			<div class="icons-box">
				<% if @place.e_outlet %>
				<div class="icon">
					<i class="fas fa-plug"></i>
				</div>
				<% else %>
				<div class="icon-false">
					<i class="fas fa-plug"></i>
				</div>
				<% end %>
			</div>

			<div class="icons-box">
				<% if @place.access_handi %>
					<div class="icon">
						<i class="fas fa-wheelchair"></i>
					</div>
				<% else %>
					<div class="icon-false">
						<i class="fas fa-wheelchair"></i>
					</div>
				<% end %>
			</div>

		</div>

		<div class="d-flex justify-content-around">

			<% if !@place.price %>
			<span class="badge badge-pill badge-pill-info"><i class="fas fa-euro-sign"></i></span>
			<% else %>
			<span class="badge badge-pill badge-pill-info"><i class="fas fa-euro-sign"></i><i class="fas fa-euro-sign"></i><i class="fas fa-euro-sign"></i></span>
			<% end %>

			<span class="badge badge-pill badge-pill-info"><i class="fas fa-music"></i> <%= @place.vibe %></span>

			<% if @place.vegan %>
			<span class="badge badge-pill badge-pill-info">vegan</span>
			<% else %>
			<span class="badge badge-pill badge-pill-false">vegan</span>
			<% end %>
		</div>

	</div>


</div>

app/views/places/components/_promoted_places.html.erb
<section id="portfolio" class="clearfix">
    <div class="container">

      <header class="section-header">
        <h3 class="section-title">Les lieux de la semaine</h3>
      </header>

      <div class="row">
        <div class="col-lg-12">
          <ul id="portfolio-flters">
            <li data-filter=".filter-close">Le plus proche</li>
            <li data-filter=".filter-liked">Le plus apprécié</li>
          </ul>
        </div>
      </div>

      <div class="row portfolio-container">

        <div class="col-lg-6 portfolio-item filter-close">
          <div class="portfolio-wrap">
            <div class="card">
              <% if place_closer.pictures.attached? %>
                <%= image_tag place_closer.pictures.first, alt: 'picture', class:"d-block w-100 card-img-top"  %>
              <% else %>
                <%= image_tag "coffee-shop.jpg", class:"d-block w-100 card-img-top" %>
              <% end %>
              <div class="card-body">
                  <h5 class="card-title"><%= link_to place_closer.name, place_path(place_closer.id) %></h5>
                <p class="card-text"><%= place_closer.description.truncate(70) %></p>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-6 portfolio-item filter-liked">
          <div class="portfolio-wrap">
            <div class="card">
                <% if place_top_fav.pictures.attached? %>
                  <%= image_tag place_closer.pictures.first, alt: 'picture', class:"d-block w-100 card-img-top"  %>
                <% else %>
                  <%= image_tag "coffee-shop.jpg", class:"d-block w-100 card-img-top" %>
                <% end %>
              <div class="card-body">
                  <h5 class="card-title"><%= link_to place_top_fav.name, place_path(place_top_fav.id) %></h5>
                <p class="card-text"><%= place_top_fav.description.truncate(70) %></p>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  </section>