config/routes.rb
Rails.application.routes.draw do
  get 'statics/team'
  get 'statics/favoris'
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'home#index'

  resources :places do
    resources :pictures, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :addresses

  resources :admins, only: [:index]
  #get 'dashboard_test', to: "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/components/_footer.html.erb
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row d-flex justify-content-around">

        <div class="col-lg-4 col-md-12 footer-info">
          <h3>Work & Koffee</h3>
          <p>Work & Koffee est l'application mobile qui vous aide à trouver l'endroit idéal pour travailler à Montpellier. Grâce à nos suggestions personnalisées, que vous soyez adeptes d'endroits atypiques ou plus classiques, vous ne perdrez plus une minute à chercher LE bon spot pour travailler !</p>
          <br>
          <p>© All rights reserved</p>
        </div>

        <div class="col-lg-2 col-md-6 footer-links text-center">
          <h4>Liens utiles</h4>
          <ul>
            <%if user_signed_in?%>
              <li><%= link_to "Accueil", places_path %></li>
              <li><%= link_to "L'équipe", statics_team_path %></li>
            <%else%>  
              <li><%=link_to "Se connecter", new_user_session_path %></li>
              <li><%=link_to "S'inscrire", new_user_registration_path %></li>
            <%end%>  
          </ul>
        </div>

        <div class="col-lg-3 col-md-6 footer-contact text-right">
          <h4>Nous contacter</h4>
          <p>
            5 Place du Peyrou <br>
            Montpellier, 34000 <br>
            France <br>
            <strong>Téléphone:</strong> 04 67 55 89 55<br>
            <strong>Email:</strong><a href="mailto:bonjour@work-and-koffee.com"> bonjour@work-and-koffee.com<br>
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/components/_navbar.html.erb
<header id="header" class="fixed-top">
  <div class="container">

    <div class="logo float-left">
      <%= link_to places_path do %>
        <%= image_tag "logo3.png", class: "scrollto" %>
      <% end %>  
    </div>

    <nav class="main-nav float-right d-none d-lg-block">
      <ul>
        <%if user_signed_in?%>
          <li><%= link_to "Accueil", places_path %></li>
          <li><%= link_to "L'équipe", statics_team_path %></li>
          <li><%= link_to "Mes favoris", statics_favoris_path %></li>
          <li><%=link_to "Mon profil", edit_user_registration_path %></li>
          <li><%=link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
        <%else%>
          <li><%=link_to "Se connecter", new_user_session_path %></li>
          <li><%=link_to "S'inscrire", new_user_registration_path %></li>
        <%end%>
      </ul>
    </nav>

  </div>
</header>