config/routes.rb
Rails.application.routes.draw do
  get 'statics/team'
  get 'statics/favoris'
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'home#index'

  resources :places do
    resources :pictures, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :addresses

  resources :admins, only: [:index]
  #get 'dashboard_test', to: "dashboard#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord

	has_many_attached :pictures
  belongs_to :address

  validates :name, presence: true
	validates :description, presence: true
	validates :address_id, presence: true

  validates :vibe, inclusion: { in: %w(hip_hop classic exotique lounge electronique pop) } 

  

  
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  
  def index
    @places = Place.all
    @user_like = Like.where(user_id: current_user.id)
    @like = []
    @user_like.each do |like|
      @like << like.place_id
    end 

  end

  def new
  end

  def create
  end

  def edit
    @place = Place.find(params[:id])  
  end

  def show
    @place = Place.find(params[:id])
    @user_like = Like.where(user_id: current_user.id)
    @like = []
    @user_like.each do |like|
      @like << like.place_id
    end 
  end


  def update
    @place = Place.find(params[:id])  
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_path(@place) }
        # format.json { render :edit, status: :ok }
      else
        format.html { render :edit }
        # format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path
  end


  def place_params
    params.require(:place).permit(:name, :description, :wifi, :vibe, :vegan, :access_handi, :price, :e_outlet, images: [])
  end


end

app/helpers/places_helper.rb
module PlacesHelper

    public

    def url_map
        url= "<iframe width=\"100%\" height=\"350\" frameborder=\"0\" style=\"border:0\"
        src=\"https://www.google.com/maps/embed/v1/place?key=#{ENV['KEY_GOOGLE_MAP']}&q=#{current_address.latitude},#{current_address.longitude}\" allowfullscreen></iframe>"
    end

    def places_match
        @all_places = Array.new
        @select_places = Array.new
        @tmp_places = Array.new 

        store_all_places(@all_places)
        @tmp_places = @all_places
        keep_wifi_places
        keep_price_places
        keep_eOutlet_places
        keep_access_handi_places
        keep_vibe_places
        keep_vegan_places
        cut_array(sort_by_distance(@tmp_places).reverse)
      end
    
      def place_closer
        sort_by_distance(@all_places)
        @all_places.last
      end
    
      def place_top_fav
        places_all = Array.new
        store_all_places(places_all)
        places_all.sort_by!{|place| place.liked_count}
        places_all.last
      end

      private

      def cut_array(array)
        if (array.length > 3)
          return array[0, 3]
        end
        return array
      end
    
      def sort_by_distance(array_of_places)
        array_of_places.sort_by!{ |place| address_of_place(place).bearing_from(address_of_user(current_user))}
      end
    
      def address_of_place(place)
        Address.find(place.address_id)
      end
    
      def address_of_user(user)
        Address.find(current_user.address_id)
      end
    
      def keep_wifi_places
        @tmp_places.each do |place|
          if ((place.wifi != current_user.wifi) && (current_user.wifi))
            if (@tmp_places.length > 3)
              delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_price_places
        @tmp_places.each do |place|
          if (place.price != current_user.price) && (!current_user.price)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_eOutlet_places
        @tmp_places.each do |place|
          if (place.e_outlet != current_user.e_outlet) && (current_user.e_outlet)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_access_handi_places
        @tmp_places.each do |place|
          if (place.access_handi != current_user.access_handi) && (current_user.access_handi)
            delete_place_from_array(place, @tmp_places)
          end
        end
        return nil
      end
    
      def keep_vibe_places
        @tmp_places.each do |place|
          if (place.vibe != current_user.vibe)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def keep_vegan_places
        @tmp_places.each do |place|
          if (place.vegan != current_user.vegan)
            if (@tmp_places.length > 3)
                delete_place_from_array(place, @tmp_places)
            end
          end
        end
        return nil
      end
    
      def delete_place_from_array(place, array)
        index_of_place = array.index(place)
        array.slice!(index_of_place)
        return nil
      end
    
      def store_all_places(places_array)
        Place.all.each do |place|
          places_array.push(place)
        end
      end
    
     
   
    def current_place
        Place.find(params[:id])
    end
    
    def current_address
        Address.find(current_place.address_id)
    end

    
end

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/delete.html.erb
<h1>Places#delete</h1>
<p>Find me in app/views/places/delete.html.erb</p>

app/views/places/edit.html.erb
</br>
</br>
</br>
</br>

<%= form_for @place do |f|%>
  <div class="form-group mt-5">
      <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="from-group">
      <div class="control-label"><h6> Les caractéristique </h6> </div>
          <label class="custom-switch mt-2">
            <%= f.check_box :wifi, class: 'custom-switch-input' %>
            <span class="custom-switch-indicator"></span>
            <span class="custom-switch-description">Wifi</span>
          </label>
          <label class="custom-switch mt-2">
            <%= f.check_box :e_outlet, class: 'custom-switch-input' %>
            <span class="custom-switch-indicator"></span>
            <span class="custom-switch-description">Prises éléctriques</span>
          </label>
          <label class="custom-switch mt-2">
            <%= f.check_box :price, class: 'custom-switch-input' %>
            <span class="custom-switch-indicator"></span>
            <span class="custom-switch-description">Prix</span>
          </label>
          <label class="custom-switch mt-2">
            <%= f.check_box :vegan, class: 'custom-switch-input' %>
            <span class="custom-switch-indicator"></span>
            <span class="custom-switch-description">Vegan</span>
          </label>
          <label class="custom-switch mt-2">
            <%= f.check_box :access_handi, class: 'custom-switch-input' %>
            <span class="custom-switch-indicator"></span>
            <span class="custom-switch-description">Acces aux personnes à mobilité réduite</span>
          </label>
          <button type="submit", class="btn col-sm-4 btn-success btn-block"> Editer un lieu </button>
          <!-- <%= submit_tag "Modifier le lieu", class: 'btn col-sm-8 btn-success btn-block' %> -->
      </div>
    </div>

<!-- UTILISER LE CODE POUR AFFICHER LES IMAGES LIEES AU LIEU -->
<section>

  <div class="container mt-4">
    <div class="row">
      <div>
        <h3>Les photos de cet endroit</h3>

        <%if @place.pictures.attached?%>

          <%@place.pictures.each do |pic|%>
            <%= image_tag pic, alt: 'picture' %>
          <%end%>

        <%else%>
          <p>========== Il n'y a pas encore de photos de cet endroit =========</p>
          <p>==== Vous avez pris des photos lors de votre dernière visite ? ====</p>
          <p>======== Postez les pour donner envie aux utilisateurs ! ========</p>
        <%end%>

        <h3>Vous souhaitez ajouter des photos ?</h3>
        <%= form_tag place_pictures_path(@place), multipart: true do %>
        <%= file_field_tag :pictures, :multiple => true %>
        <%= submit_tag "mettre à jour" %>
        <% end %>
      </div>
    </div>
  </div>
</section>


<% end %>

app/views/places/index.html.erb
<section class="matches-index pt-5">
	<div class="container">
		<div class="row d-block">
			<h1>Voici les lieux qui correspondent à tes critères</h1>
		</div>

		<%= render "places/components/portfolio_places"  %>

		<%= render "places/components/promoted_places"  %>		

	</div>
</section>

app/views/places/new.html.erb
<h1>Places#new</h1>
<p>Find me in app/views/places/new.html.erb</p>

app/views/places/show.html.erb
    <%= render "places/components/header_place_show"  %>

<section id="about">
	<div class="container">

		<header class="section-header">
			<h3>Découvrir l'endroit</h3><br>
			
		</header>

    <%= render "places/components/presentation_place"  %>

    <%= render "places/components/location_place"  %>

	</div>
</section>

<%= render "places/components/comments"  %>